"""create ticket_status_history table

Revision ID: f2caf8df4e26
Revises: 7ea037cba603
Create Date: 2026-10-06 16:39:13.443252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'f2caf8df4e26'
down_revision: Union[str, None] = '7ea037cba603'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_status_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('changed_by_id', sa.Uuid(), nullable=True),
    sa.Column('old_status', postgresql.ENUM('open', 'in_progress', 'resolved', 'closed', name='ticket_status', create_type=False), nullable=True),
    sa.Column('new_status', postgresql.ENUM('open', 'in_progress', 'resolved', 'closed', name='ticket_status', create_type=False), nullable=True),    sa.Column('old_agent_id', sa.Uuid(), nullable=True),
    sa.Column('new_agent_id', sa.Uuid(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['new_agent_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['old_agent_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_status_history_ticket_id'), 'ticket_status_history', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_status_history_ticket_id'), table_name='ticket_status_history')
    op.drop_table('ticket_status_history')
    # ### end Alembic commands ###
